Mudando muita coisa
dev-house-community/ThasfinBot pull request #10
Opened 2021-04-17 22:54 UTC by geovanipfranca

# Refactor pesadissimoooo

### Bom o que foi alterado nesse commit:

- [x] Patterns
- [x] Multiplos alias para comando
- [x] Multiplas respostas por comando
- [x] Comando em JSON com render pelo mustache com async
- [x] Criando comando !foco pra quando a Jake perde o foco
- [x] Possibilidade de criar comandos diferentes para cada canal seguindo o arquivo `commands.CANAL.json` onde o canal é o dinâmico
- [x] Low DB para salvar o count sem a necessidade de um banco de dados
- [x] Colocando mensagem de inicio no chat quando o bot inicia
- [ ] Colocar os testes funcionais (com testes não só arquivo) das alterações

### Se pegar fogo não me responsabilizo 🙅🏻‍♂️ 
![Famoso I's Fine pegando fogo no fundo!](https://media.giphy.com/media/QMHoU66sBXqqLqYvGO/giphy.gif)

2021-04-18 00:02 UTC, DevRadhy requested changes
Separar os comandos do prefixo, para que futuramente possa mudar o prefixo por comando, ou caso precise mudar por código, possa-se mudar em um único lugar.

2021-04-18 00:05 UTC, DevRadhy commented
por exemplo,
```js
// Definição de prefixo
{
  prefix: "!"
}

// Arquivo de comandos
{
  name: "discord", // Nome dos comandos
  ...
}
```

2021-04-18 01:08 UTC, DevRadhy approved these changes
LGTM; thanks!

2021-04-21 14:42 UTC, caio-emidio commented
Indico para os proximos pull requests e commits nos atentarmos aos nomes e titulos.
isso pode ajudar mto para verificacao. Do que voce quis fazer. E tambem linkar a partir de agora as issues que seu PR esta arrumando.

Exemplo que talvez podemos seguir eh:
Para PullRequest
https://namingconvention.org/git/pull-request-naming.html

Para Commits
https://namingconvention.org/git/commit-message-naming.html

2021-04-22 11:40 UTC, caio-emidio reviewed
Fiz alguns comentarios. Acredito que essas mudancas possam ajudar.

2021-04-22 11:42 UTC, jakeliny commented on src/app.js
> +  console.log(`*** Bot conectado com sucesso no IRC (${address}:${port}} nos canais [${options.channels}]`);
Por enquanto esse console.log em especifico é importante, mas realmente é uma boa criar um logger no futuro #27

2021-04-22 11:47 UTC, jakeliny requested changes

2021-04-22 11:53 UTC, caio-emidio commented on src/utils.js
> +    if (Array.isArray(cmd) && cmd.length > 0) {
Ambos os ifs dessa function o ideal seria fazer um Decompose Conditional
https://refactoring.guru/decompose-conditional

2021-04-22 11:53 UTC, caio-emidio commented on src/utils.js
> +    if (Array.isArray(cmd) && cmd.length == 0) {
Ambos os ifs dessa function o ideal seria fazer um Decompose Conditional
https://refactoring.guru/decompose-conditional

2021-04-22 11:53 UTC, caio-emidio commented on src/utils.js
> +    if(action.split("")[0] == "!") { action = action.substring(1,action.length); }
os if dessa function o ideal seria fazer um Decompose Conditional
https://refactoring.guru/decompose-conditional

2021-04-22 11:53 UTC, caio-emidio commented on src/useCommands/count/count.js
> +    if (!Number.isNaN(increment)) { if (increment > MAX_COUNT || increment <= 0) increment = 1; }
Essa regra de nested tb podemos dar uma melhorada.
https://refactoring.guru/replace-nested-conditional-with-guard-clauses

2021-04-22 11:55 UTC, jakeliny approved these changes

2021-04-22 11:55 UTC, jakeliny commented on src/utils.js
> +const getCommandByAction = (action, ignored, commands) => {
As funções desse arquivo ficaram um pouco confusas, comenta as funções pra eu entender melhor pf

2021-04-22 11:57 UTC, jakeliny requested changes
As funções desse arquivo ficaram um pouco confusas, comenta as funções pra eu entender melhor pf

2021-04-22 11:57 UTC, caio-emidio commented on src/utils.js
> +    if(action.split("")[0] == "!") { action = action.substring(1,action.length); }
https://www.w3schools.com/jsref/jsref_startswith.asp
if(str.startsWith("!")) nao faria a mesma coisa?

2021-04-22 12:02 UTC, caio-emidio commented on src/database/index.js
> +const path = require("path")
Eu tava vendo... se a @jakeliny aplicar o PR #9 . Vc pode ignorar isso aqui q a gente resolve com um alt + shift + F. de uma vez soh ;)

2021-04-22 12:02 UTC, caio-emidio commented on src/useCases/initTemplates/initTemplates.js
> +const path = require("path")
Eu tava vendo... se a @jakeliny aplicar o PR #9 . Vc pode ignorar isso aqui q a gente resolve com um alt + shift + F. de uma vez soh ;)

2021-04-22 12:05 UTC, caio-emidio commented on src/utils.js
> +    if (Array.isArray(cmd) && cmd.length > 0) {
Caso tenha duvidas do que eh...
na linha 22 vc colocaria um: "const isCmdArrayNotEmpty = Array.isArray(cmd) && cmd.lenght > 0;"
e na linha 23 vc faria: "if(isCmdArrayNotEmpty) { "

2021-04-22 12:06 UTC, caio-emidio commented on src/utils.js
> +    if (Array.isArray(cmd) && cmd.length == 0) {
E dai aqui teoricamente algo como "isCmdEmptyArray"

2021-04-22 12:08 UTC, caio-emidio commented on src/useCommands/count/count.js
> +    if (!Number.isNaN(increment)) { if (increment > MAX_COUNT || increment <= 0) increment = 1; }
Aquelas regras de decompose conditional q falei ali em cima pode ajudar... 
Vai dexar o codigo bem limpo e acho que da pra deixar no mesmo if.

2021-04-22 12:13 UTC, geovanipfranca commented on src/useCommands/ajuda/ajuda.js
> +const utils = require("../../utils")
Deixei ajuda em português, porque a palavra help poderíamos usar em uma ajuda em inglês, mas podemos deixar help mesmo, não tem problema

2021-04-22 12:13 UTC, geovanipfranca commented on src/utils.js
> +    if(action.split("")[0] == "!") { action = action.substring(1,action.length); }
Faria sim

2021-04-22 12:14 UTC, geovanipfranca commented on src/useCases/handleCommands/handleCommands.js
> +  let req = receivedMessage.split(" ")
Vamos mudar pra const

2021-04-22 14:06 UTC, caio-emidio commented on src/utils.js
> +    if(action.split("")[0] == "!") { action = action.substring(1,action.length); }
Acredito que fica mais legivel e de facil intendimento.
E tenta usar sempre "===" ao inves "==" se for o caso.

2021-04-24 22:28 UTC, jakeliny requested changes

2021-04-24 22:28 UTC, jakeliny commented on src/app.js
> +    options.startup.forEach(m => this.say(channel, m));
```suggestion
    options.startup.forEach(msg => this.say(channel, msg));
```

2021-04-24 22:28 UTC, jakeliny commented on src/useCases/handleCommands/handleCommands.js
> +  if (!receivedMessage.startsWith("!")) return;
Maraviwonderful

2021-04-27 17:02 UTC, jakeliny submitted a review, later dismissed
Vamos abrir algumas issues para melhorar alguns pontos, do restante tudo está funcionando, acho que podemos seguir

2021-04-27 19:27 UTC, caio-emidio submitted a review, later dismissed
Aprovado.

2021-04-27 19:32 UTC, jakeliny approved these changes

2021-04-27 19:36 UTC, caio-emidio approved these changes

2021-04-27 19:36 UTC, merged